name: rsync action to sync files to remote server
inputs:
  destination:
    description: "Destination directory to sync"
    required: true
  host:
    description: "Remote server host"
    required: true
runs:
  using: "composite"
  steps:
    - name: Rsync
      shell: bash
      run: |
        for SERVER in $HOSTIPS; do
          echo "Syncing to $SERVER"
          rsync -Pavzc -e "ssh -i ~/non-prod-key" --update scripts/* ec2-user@${{ inputs.host }}:${{ inputs.destination }}
        done
           
