name: rsync action to sync files to remote server
inputs:
  source:
    description: "Source directory to sync"
    required: true
  destination:
    description: "Destination directory to sync"
    required: true
  host:
    description: "Remote server host"
    required: true
  username:
    description: "Remote server username"
    required: true
runs:
  using: "composite"
  steps:
    - name: Rsync
      run: |
        if [[ -n $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }}) | grep "scripts/*" ]]; then
          for SERVER in ${{ inputs.host }}; do
            rsync -Pavz -e /home/ec2-user/non-prod-key --update scripts/* ${{ inputs.username }}@${{ inputs.host }}:${{ inputs.destination }}
