name: Sync files to Ec2 servers

on:
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ghar
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Server IP Display
        run: echo "Hosts: ${{ vars.hosts }}"
          
      - name: Sync files
        uses: ./.github/rsync-action/
        with:
          source: "./"
          destination: "/home/ec2-user/sync-folder"
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
