name: Sync files to Ec2 servers
on:
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync files
        uses: ./.github/resuable-actions/rsync-action/
        with:
          source: "./"
          destination: "/home/ubuntu/sync-folder"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
